name: visualize-type-inference
version: 0.0.1.0

author: Andreas Abel
copyright: Andreas Abel, 2024

synopsis: Simulate simple constraint-based type inference
description:
  Constraint-based inference for simple types is traced step-by-step,
  both for the original algorithm J that eagerly applies substitutions
  gained from unification, and a more modern conception that
  separates constraint generation from constraint solving.
category: Teaching

github: teach-plt/visualize-type-inference

executable:
  source-dirs: src
  main: Main.hs
  when:
    condition: false
    other-modules:
    - Lam.ErrM
    - Lam.Skel
    - Lam.Test

dependencies:
- base >= 4.15 && < 5
- ansi-terminal
- array
- containers
- mtl
- optparse-applicative
- prettyprinter
- prettyprinter-ansi-terminal
- string-qq

build-tools:
- alex
- happy

language: Haskell2010
default-extensions:
- BlockArguments
- FlexibleInstances
- ImportQualifiedPost
- LambdaCase
- MultiWayIf
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- TypeSynonymInstances

tested-with:
- GHC == 9.12.2
- GHC == 9.10.3
- GHC == 9.8.4
- GHC == 9.6.7
- GHC == 9.4.8
- GHC == 9.2.8
