name: visualize-type-inference
version: 0.0.0.0

executable:
  source-dirs: src
  main: Main.hs
  when:
    condition: false
    other-modules:
    - Lam.ErrM
    - Lam.Skel
    - Lam.Test

dependencies:
- base
- ansi-terminal
- array
- containers
- mtl
- optparse-applicative
- prettyprinter
- prettyprinter-ansi-terminal
- string-qq

language: Haskell2010
default-extensions:
- BlockArguments
- FlexibleInstances
- ImportQualifiedPost
- LambdaCase
- MultiWayIf
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- TypeSynonymInstances

tested-with:
- GHC == 9.12.2
- GHC == 9.10.3
- GHC == 9.8.4
- GHC == 9.6.7
- GHC == 9.4.8
- GHC == 9.2.8
